### ISSUE TITLE
Contributor/Supporter - Navigation/Footer/Homepage - Remove unused links and add email to footer

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#104]
## Background
We can just remove the contact and about sections. Drop both links from the Nav and remove the About section from the Homepage. 

## Scenario: A user navigate to incentivize
- [x] When I land on the Homepage
- [x] Then I  
  - [x] Do not see an About Link in the Nav
  - [x] Do not see a contact link in the nav
  - [x] Do not see an About section on the Homepage
  - [x] see a link to email incentivize@revelry.co in the footer

**Comment by gerardramos** [comment]
remove contact from the main nav. We don't need a contact section/page/form.

All we need is a mailto link to email incentivize@revelry.co in the footer.
