### ISSUE TITLE
Incentivize - Stellar - Incentivize Stellar Account

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#105]
## Background 
Incentivize needs it's own Stellar account to interact/transact with Project Fund Accounts. This is for creating that account and storing Environment Variables in the app. 

## Scenario: Incentivize Stellar Account
Given I am Incentivize
- [ ] When I interact with the Stellar network
- [ ] Then I have an account to do so
- [ ] And this account info is not stored in the app or the database but in the environment

**Comment by bryanjos** [comment]
Self scoring as a 2. Env vars can be checked by @jwietelmann so going to assign to him

**Comment by Mcscott142** [comment]
I see ENV vars in deis. Closing.
