### ISSUE TITLE
Developer - Prod App - Spin up a new Production App on Stellar Public network

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#115]
## Background
Right now incentivize.io is pointed at the staging site and using the stellar testings platform. This ticket Will cover spinning up a new application for production and using the stellar public network. 

- [x] Production Deis App
- [ ] Database
- [x] Production Github App
- [ ] Admin Stellar Account
- [ ] Update DNS settings

**Comment by bryanjos** [comment]
Going to make it so pushes to master still go to staging. Production deployments will happen when a tag is made

**Comment by bit-herder** [comment]
any risks here? do we have an idea of the traffic this might generate?
