### ISSUE TITLE
Unable to connect Repo, getting 403

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#126]
## Background 
Using https://github.com/Mcscott142/breakable_toy/ I am unable to connect a webhook to my Repo. Getting 403 Forbidden. Could this be because of the `incentivize.io` URL?

![webhook_ _https___incentivize_io_github_webhooks](https://user-images.githubusercontent.com/6877299/44106601-b916021c-9fba-11e8-8b34-2d93680a4078.png)

![webhook_ _https___incentivize_io_github_webhooks](https://user-images.githubusercontent.com/6877299/44106608-bfa19a88-9fba-11e8-948b-b06878313170.png)

![incentivize](https://user-images.githubusercontent.com/6877299/44106667-e759d1e4-9fba-11e8-83c2-5c316a1599c9.png)

**Comment by bryanjos** [comment]
Case-insensitive bug. This should work now
