### ISSUE TITLE
Incentivize - Contributions - Schedule Processing of Contribution

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#128]
GIVEN Incentivize has received a webhook from GitHub
AND it qualifies as a contribution
THEN a scheduled task is created to process contribution

**Comment by bryanjos** [comment]
Thinking of either using [Rihanna](https://hex.pm/packages/rihanna) or [Ecto Job](https://hex.pm/packages/ecto_job) for job queue

**Comment by iamjoshfrank** [comment]
@bryanjos - I'm not sure how to test this as an end user based on the scenario.

If I have a project with a supporting fund and actions attached; and I perform one of the incentivized actions in the project repo; then will I see an end-user facing result?

**Comment by bryanjos** [comment]
I guess the best thing to do would be to test for regressions. As in make sure that contributions are still paid out

**Comment by Mcscott142** [comment]
Able to see Lumens decreasing from fund and increasing in my test Stellar Account. Assuming that suffces for this to pass. Closing.
