### ISSUE TITLE
Product Owner / Product Manager - Project Brief - First Draft of Core Loop Model

### ISSUE THREAD

**Issue by gerardramos** [revelrylabs/incentivize#13]
## Background
Goal: add content to `README.md` in the section `Project Brief > What is the core loop?`

We use [Camuda](https://camunda.com/download/) to create the Core Loop BBMN. Editable Camuda files are saved as `.bpm`. Also, share a JPG, PNG screenshot or exported PDF of the chart so the team can easily view and access.

## Scenario: Add Core Loop to Project Brief
Given I am a PM
- [x] When I view the Project Brief
- [x] Then I see the core loop explanation
- [x] And I see links to the Core Loop:
  - [x] native Core Loop BPMN
  - [x] link to Core Loop as a PDF, PNG, JPG

**Comment by iamjoshfrank** [comment]
Merged. Ready to move forward to UAT / close.
