### ISSUE TITLE
As a Linux user on incentivize.io, I see a scroll bar under the menu

### ISSUE THREAD

**Issue by grossvogel** [revelrylabs/incentivize#134]
## Description

I know this platform isn't officially supported per the readme, but I thought I'd document what I found anyway: Using Linux on Chrome or Firefox, I see scrollbars on the menu on a desktop monitor.

## Screenshots/Gifs

![incentivize](https://user-images.githubusercontent.com/802805/44125710-aee53954-9ff9-11e8-9a63-2354ed4a2648.png)

![incentivize-firefox](https://user-images.githubusercontent.com/802805/44125746-e9b56a86-9ff9-11e8-9ff6-25d4a07e39ad.png)

## Steps to Reproduce

Load any page on the site. I'm seeing it whether I'm logged-in or out.

## Platform/Device/Browser Information

- [X] Platform: Ubuntu Trusty
- [X] Device: Desktop
- [X] Browser (if found on web application): Chrome & Firefox

**Comment by jwietelmann** [comment]
Going forward past the show-it-off period we should officially support Linux. This seems like the kind of system that is going to skew heavier toward Linux users than your average.
