### ISSUE TITLE
Fix Login Re-direct issues

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#138]
## Background
There are a few issues with Links and the incentivize.io url.
### Redirects to staging url
1) Navigate to https://incentivize.io/
2) Select Login
3) The redirect is to https://incentivize.stage.revelry.net/account

**Comment by bryanjos** [comment]
Someone with admin privileges to oauth app will have to update the url for the redirect

**Comment by Mcscott142** [comment]
Oh right. I'll go through everything that's in there and Tag folks who need to update them. Mostly me.

**Comment by bryanjos** [comment]
For unauthorized, this is correct without being logged in. We can make it friendlier though. We can redirect to the home page with a flash message maybe

**Comment by Mcscott142** [comment]
@jwietelmann Can you update the Oauth URL for re-direct?

**Comment by jwietelmann** [comment]
Should be good to go now. Check me.

**Comment by Mcscott142** [comment]
👍 , closing.

**Comment by bryanjos** [comment]
@jwietelmann confirmed! Did you happen to change the name of the OAuth app too? I noticed when I gave permission, it says incentive-staging. Maybe we should name it `Incentivize (Test)` or something
