### ISSUE TITLE
New User - Log In - Make OAuth App Name Less Sketch

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/incentivize#150]
## Background

As a new user choosing "Log In" in incentivize.io, I'm automatically re-directed to authorize the app via GitHub (great!). But I'm leery of giving access to an app called `Incentivize-Staging`.

<img width="535" alt="screen shot 2018-08-16 at 1 30 25 pm" src="https://user-images.githubusercontent.com/10236515/44229735-81b63580-a15e-11e8-9eaf-aa8fb0773b2f.png">

I'll suggest a scenario below, but offer a more general problem statement:

_I want to feel confident when I sign up for Incentivize that I am connecting a legitimate application._

## Scenario: Authorize Incentivize to Access GitHub Account

Given I am a new user
- [x] When I click "Log In"
- [x] and When I am redirected to GitHub's authorization page
- [x] Then I see an updated app name that gives me confidence that it is safe to authorize

**Comment by bryanjos** [comment]
Requires someone with admin privileges to github oauth app to change the name

**Comment by bryanjos** [comment]
This should now be "Incentivize (Stellar Testnet)"

**Comment by iamjoshfrank** [comment]
Logged in today, LGTM and I feel more confident connecting my account.
