### ISSUE TITLE
Incentivize Retro 8-20-18

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#152]
## Background
Wanted to get a Retro in but don't want to take any more hours for Week 33. Scheduling for Monday 8-20. 

If anyone has notes they want to go ahead and get down please drop them on this ticket. 

>Our goal with retros are not to re-live situations, but to acknowledge the pain points within our work while identifying how we can take action to reduce or eliminate the impact. Also, we should acknowledge things that are working really well and identify ways we can increase the impact of what is working well.

## Retro Structure
- What went poorly?
- What went well?
- How can we improve: reduce/eliminate the poor; amplify the great?

**Comment by Mcscott142** [comment]
## Poorly
Colin:
- G not super available all the time, that left some questions open
- App submission could have gone smoother
- Better Job at documenting decisions	

Brittany: 
- beginning of the project was confusing
- directions from multiple conflicting sources resulted in wasted hrs
- With limited hrs resourced, it caused some anxiety. Nervous about progress

Bryan:
- Project start was confusing. Didn't quite understand the goal or the product.
- Time was short, nobody was full time so there was no real practical time to talk to people e.g. design discussion with Brittany


## Good
Brittany: 
- we were getting things done at a good pace
- The project was smoother as we went along

Bryan:
- took a while to get to the core loop but did a good job of prioritizing towards the core loop
- we now have some good experience with stellar and can tell people

Colin: 
- Everyone was vocal, good communication
- The project went as smooth or smoother than any I have been on considering the timeline
- Everyone mostly stayed w/in allocated hrs and got MORE than the sprint commitments completed

Thomas 
Bad/Good crossover
- In the beginning, we started going down paths that were more complicated than necessary, saved ourselves by reeling it back in solving the core problem

## Take-Aways
Colin:
- Document decisions better and ON GitHub tickets to they don't get lost or forgotten
Thomas:
- Find someway to bake into reusable stories? a way to keep us focused on the core loop problem solving. "ship a damn thing then go get weird" - @thomasknoll #qotd

## Additional Concerns
Bryan: Where do we go from here? Don't want the project to wither and die
	- raise fire drill if we're worried about it
	- no official resourcing for the time being
	- It is open source and contributions will be tracked

**Comment by thomasknoll** [comment]
https://github.com/revelrylabs/reusable-stories/pull/134
