### ISSUE TITLE
Developer - GitHub Integration - Use GitHub App for Login

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#156]
## Background
Incentivize currently uses a GitHub OAuth app. We want to move towards using a GitHub app (#96). This will be the first step towards that by using a GitHub app to control logging in via GitHub

We do not need a Marketplace listing so this could remove the unknowns. 

## Scenario: Use a GitHub App instead of an OAuth App for Logging in
- [x] When I go to login
- [x] Then I am authorized using a github app instead of an OAuth app

**Comment by iamjoshfrank** [comment]
Confirmed by logging in since the change. Had to re-authorize the app. Now when I navigate to https://github.com/settings/apps/authorizations I see **Incentivize (Stellar Testnet)** listed in the `Authorized GitHub Apps` tab.
