### ISSUE TITLE
Repo Admin - Repository - Enforce public repos

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#157]
To make sure no one accidentally adds a private repo for now, we should enforce that only public repos are added.

# Scenario: Add a public github repo
- [x] GIVEN I try to add a repository
- [x] AND that repository is public
- [x] THEN the repo is added 

# Scenario: Disallow private repo
- [ ] GIVEN I try to add a repository
- [ ] AND that repository is private
- [ ] THEN the repo is not added 
- [ ] AND I see a validation message saying as much

**Comment by iamjoshfrank** [comment]
Successfully added my test public repo and stumbled my way to verify it was listed at https://incentivize.io/repos/iamjoshfrank/hello-world-public (opened #164 to smooth out this workflow).

Will test private repo after getting a question answered.

**Comment by iamjoshfrank** [comment]
Successfully added my test public repo and stumbled my way to verify it was listed at https://incentivize.io/repos/iamjoshfrank/hello-world-public (opened #164 to smooth out this workflow).

Will test private repo after getting a question answered.

**Comment by iamjoshfrank** [comment]
Blocking this b/c an upcoming PR on #162 will likely remove the private option entirely (for now).

**Comment by bryanjos** [comment]
This is technically not blocked anymore, but also may not be invalid with #162 now
