### ISSUE TITLE
Repo Admin - Connect a Repository - Button or Redirect to Incentivize Project Page

### ISSUE THREAD

**Issue by iamjoshfrank** [revelrylabs/incentivize#164]
## Background
While testing #157, I relized that our "Connect a Repository" page provides nothing more than instructions. We need to have some sort of culminating action on the page that helps the user know they are "done."

This could take the form of instructions like:
```When you have created the webhook, click "Continue" to see your project listing on Incentivize```
followed by a button with a label "Continue" and a re-direct to the resulting project page on Incentivize.

Or some other solution. The problem we're trying to solve here is to provide the Repo Admin a confirmation step so they can see the result of connecting the repo.

**Comment by bryanjos** [comment]
Since connecting repos changed now, this is no longer valid
