### ISSUE TITLE
Supporter - Permissions - Create an Organization

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#173]
Incentivize needs the ability for users to add organizations such as Revelry so that a full team can be rewarded for contributing to the companies private repositories. 

We will base permissions on Rollbar's model for Organizations/Teams. Documentation for that is [here](https://docs.rollbar.com/docs/users-teams-accounts). 

This ticket will cover the creation of an Organization by an incentivize user. 

## Scenario: A user creates an Organization from their Account
- [ ] When I am on my Account page
- [ ] Then I am able to create an Organization
- [ ] And add Administrators for my Organization

**Comment by Mcscott142** [comment]
@bryanjos What are we referring to here? Like types of users? Admins etc?

**Comment by bryanjos** [comment]
The same way github has organizations and/or groups, we need a way to have users create groups so that a group of people have permission to one or more repositories and funds.

We could try using github organizations for this if needed. But seeing how we have repos and funds, maybe we should do something a bit different. Maybe rollbar's grouping is a better example.

**Comment by bryanjos** [comment]
Going to rethink this a bit and see about using the github app for permissions more

**Comment by bryanjos** [comment]
No longer needed now that #96 is done
