### ISSUE TITLE
Improve Repository Dashboard

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#175]
## Background
More detail should be added to the Repository Page. Users should be able to see stats and leaderboards for contributions/support with dollar amounts and any other metrics we can think of. 

## Scenario: A user navigates to a Project page
- [ ] When I am directed to `repos/<user>/<project>`
- [ ] Then I see:
	- [ ] the number of assets distributed
	- [ ] number of Funds created
	- [ ] the total number of contributions
	- [ ] the total number of contributors

Quick Mock from Gerard (we don't have to follow this exactly):
![mocks_-_google_drive](https://user-images.githubusercontent.com/6877299/45375833-c1d0d280-b5bb-11e8-81b0-6916be23b836.png)

**Comment by bryanjos** [comment]
Think about what to add here. We can add information first and then add UX elements after

**Comment by Mcscott142** [comment]
AC updated for approval/discussion.

**Comment by Mcscott142** [comment]
Removing leaderboard AC, scoring 8
