### ISSUE TITLE
Supporter/Contributor - Account -  Wallet

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#176]
## Background
We should allow users to keep track of their different assets (digital currencies) within incentivize so they don't have to navigate to an outside wallet to check balances etc. Contributors will want to keep track of the assets they have received from making contributions. Supporters will want to know their balances as they add incentives to projects. 

## Scenario: A user navigates from their account into their Wallet
- [ ] When I am directed to `account/wallet`
- [ ] Then I can
	- [ ] see my balances for each asset type I have
	- [ ] see my public key

**Comment by Mcscott142** [comment]
Updated AC, ready for approval/discussion
