### ISSUE TITLE
Wallet Account History

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#196]
## Background 
Users should be able to see their Account History from within their Wallet page. It should show the recent transaction history related to their accounts. 

## Scenario: A user opens their incentivize Wallet
- [ ] When I am on `account/wallets`
- [ ] Then I see my latest payment transaction history

**Comment by bryanjos** [comment]
Looking at the stellar account viewer, we need to use the `payments` function.

Something like:
```js
server.payments().forAccount("public_key").call().then(function (accountResult) { console.log(accountResult); }).catch(function (err) { console.error(err); })
```
