### ISSUE TITLE
Discover page hard to look at

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#244]
## Background
The Discover page needs to be a place where users get excited about contributing to projects. See https://www.kickstarter.com/ for some inspiration. It ought to feel like shopping in a sense. 

## Scenario: Update the layout of the Discover page with a new design
- [ ] When I look at the discover page
- [ ] Then I am interested in browing projects
- [ ] And I understand what it is I'm looking at

## Scenario: Developer/Designer Tasks
- [ ]  Pick a new layout/design for the discover page
- [ ]  Implement it

**Comment by Mcscott142** [comment]
Don't really need to SCORE this today but moving to the top of the list to discuss. I think anytime Brittany has leftover after cleaning up Tickets Bryan implements she should think about how to fix this page and go ahead and do it time permitting.

**Comment by Mcscott142** [comment]
@brittanygay I actually meant to drop this link in there. https://www.kickstarter.com/discover/recommended?ref=discovery_overlay

**Comment by brittanygay** [comment]
Pulling this in to start working on!

**Comment by brittanygay** [comment]
I'm going to save this ticket to work on if I happen to get any free time after completing all of the sprint tickets for this week.

**Comment by brittanygay** [comment]
Working on some quick mockups to get approved before starting to implement any changes
