### ISSUE TITLE
Contributor - Project Page - Logo, title, copy should show up on project details page

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#247]
dependent on #256 #257 #258 
## Background
Incentivize should have a more attractive looking project details page. This will be the page repo admins show would be contributors and supporters.

## Scenario: Visit Project Details Page
- [ ] When I visit the project details page
- [ ] Then I see all the information about the project
	- [ ] Logo
	- [ ] Title
	- [ ]  Description Copy

**Comment by bryanjos** [comment]
Inspiration when coming up with this was Kickstarter

**Comment by brittanygay** [comment]
Kickstarter link for inspiration: https://www.kickstarter.com/projects/kammok/bobcat-the-best-quilt-trail-to-travel?ref=section_design-tech_popular
