### ISSUE TITLE
Contributor - Account - Capture Account information when ready to contribute

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#254]
## Background
To make using Incentivize as fluid as possible, we want to ask contributors for their information only when needed. Right now we need at least their Stellar public key in order to send them assets for contributions.

## Scenario: Contributor wants to contribute to a project
- [ ] GIVEN I am a contributor that wants to contribute to a project
- [ ] THEN I am asked to give my email and Stellar public key if not already set

**Comment by Mcscott142** [comment]
Marking as draft. Want to re-think the contribution flow a little bit.
