### ISSUE TITLE
Revisit Nouns and Verbs

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#298]
## Background
Contributors vs Supporters is confusing. Need to change the language up to be more clear.

**Comment by bryanjos** [comment]
We should also figure out what we want to do with `repositories` as well. I keep hearing the word `project` being used instead. 

We should also clear up what we want to use to say `add assets to a repo's/project's fund`. 

I think `Contributor` is fine as it speaks to the audience. `Supporter` could be changed to `Backer`. That's the term I see used by a lot of crowd funding platforms. Maybe `Sponsor`.
