### ISSUE TITLE
Product Owner - Google Analytics - Setup

### ISSUE THREAD

**Issue by gerardramos** [revelrylabs/incentivize#4]
## Background
Use an existing or create a new Google Analytics account to track traffic on live, production site.

## Scenario: Already Setup
Given Google Analytics has been setup
- [x] When the Product Owner provides the UA number
- [ ] And the production site goes live
- [ ] Then a developer adds Google Analytics to the live, production site

## Scenario: Not Setup
Given Google Analytics has not been setup
- [ ] When the Product Owner decides on a gmail to use for their Google Analytics
- [ ] Then the PM walks the Product Owner through how to setup Google Analytics
- [ ] When a UA number has been created for the site
- [ ] And the production site goes live
- [ ] Then a developer adds Google Analytics to the live, production site

**Comment by thomasknoll** [comment]
- want a different property for join.incentivize ? otherwise can ship this in that page now
- I don't see this under the revelry account, assuming somewhere else?

**Comment by bryanjos** [comment]
Can be added via env var once prod site is live.

**Comment by Mcscott142** [comment]
Blocking until we have production up.
