### ISSUE TITLE
Designer - Web App - Create Favicons

### ISSUE THREAD

**Issue by gerardramos** [revelrylabs/incentivize#44]
<h2>If the project does not already have favicon, you will need to create one:</h2>

- [ ] create icon at 512 x 512
- [ ] the favicon does not have to include the entire logo, in fact, most times the full logo will be illegible at favicon size. Use a small element from the logo or app as the app icon.

<h2>If the project already has a favicon, or you just created one:</h2>

**Use a generator!** Devices and browsers are constantly changing and it's almost impossible to keep an up to date list of all icon sizes that are needed.

I like this one https://realfavicongenerator.net

- [ ] upload your favicon at 512 x 512 (the site says 260 x 260 but since a 512 x 512 icon gets generated, I like to err on the side of caution)
- [ ] follow instructions - you will have to make some decisions about bkgd colors for MS tile backgrounds and MacBook touchbar styles.
- [ ] continue following directions - after your images are generated, there will be details instructions for multiple way to include your favicons.
**save the favicons at the root of your project**

**Comment by brittanygay** [comment]
Keeping this on my radar. We are using a placeholder favicon (Harmonium's favicon) for now until I can switch this out

**Comment by gerardramos** [comment]
adding this to next up. replace harmonium favicon.

**Comment by brittanygay** [comment]
Working on this now

**Comment by brittanygay** [comment]
Just checked on staging, and there are still some edits I need to make. The gradient that I used from the branding files looks bad so I'm going to alter it and make it a bit darker. Pulling this back in to finish up tomorrow morning.

**Comment by brittanygay** [comment]
Updates are reflected on staging. I've checked on Chrome, Safari and Firefox, but not other browsers just yet. If I can get some more time I can check on Browserstack, etc.

**Comment by Mcscott142** [comment]
I've got icons on all the browsers I checked. Moving to UAT.
