### ISSUE TITLE
Contributor - Landing Page - I want to know what Incentivize is, how it works, and Sign In/Up

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#48]
## Background
When a user lands on the site they need to know what this thing does, how it works and the ability to sign in or up. We need to get some copy for each of these pieces. We'll be using GitHub OAuth for users.  

## Scenario: A user navigates to incentivze.io to find out what it is
- [ ] When I land on incentivize.io 
- [ ] Then I know what this product is

## Scenario: A user navigates to incentivze.io to find out how it works
- [ ] When I land on incentivize.io 
- [ ] And I have figured out what it does
- [ ] Then I know how it works

## Scenario: A Contributor wants to sign up
- [ ] When I land on incentivize.io
- [ ] Then I see an option to sign up as a contributor via GitHub

## Scenario: A Contributor wants to sign in
- [ ] When I land on incentivize.io
- [ ] Then I see an option to sign in to my account via GitHub

**Comment by brittanygay** [comment]
**Update**:
I'm getting close to finishing the landing page, there were some weird style bugs that came up after pulling in Harmonium so I've been fixing those. I hope to have this done by mid-day so we can move forward!

**Comment by brittanygay** [comment]
PR has been reviewed and merged. All changes are reflected on staging. This is now ready for QA.

**Comment by brittanygay** [comment]
@Mcscott142 we should probably create a new ticket to update the images on the landing page, but we won't be able to do that until we have some more features implemented.

**Comment by Mcscott142** [comment]
done #86. Page looks good moving to UAT.

**Comment by gerardramos** [comment]
closing this one. added a comment on #49 about nav and about section.
