### ISSUE TITLE
Repo Admin - GitHub Integration -  Allow Incentivize Webhook to Repository

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#52]
## Background
When a contributor signs in, they may add any public projects to incentivize where they are an administrator. This will make the projects available for all contributors and supporters on the platform. 

## Scenario: A Repositories Admin allows the incentivize webhook in their repository
- [ ] Given I login to incentivize
- [ ] Then I am asked to give Incentivize permission to create Webhooks

**Comment by bryanjos** [comment]
@Mcscott142 looks like this one is a non-starter. Github apps have a different webhook configuration and do not have access to the same apis. So looks like #96 is our only option. Which requires some more thinking through

**Comment by Mcscott142** [comment]
Ok, gonna close this one in reference to #96.
