### ISSUE TITLE
Developer - Monitoring - On-Call Rotation

### ISSUE THREAD

**Issue by gerardramos** [revelrylabs/incentivize#6]
## Background

We want projects to have an on-call rotation so that if there are problems, the engineers can be reached through PagerDuty.

## Scenario: PRs with passing tests get deployed when merged

WHEN I visit pagerduty
- [ ] THEN I see an on-call rotation for the project
- [ ] AND it has engineers in it

**Comment by bit-herder** [comment]
yeah i mean we cant use our current tooling for it, its too spendy /shrug more of a robert question.

**Comment by prehnRA** [comment]
Yeah, not the way we do that any more (or ever except for that one week).

So long as we have tickets for properly setting up rollbar & datadog we're probably a-ok to close out this one (those alerts go to places where people see them and we can do something about them).

**Comment by bryanjos** [comment]
Closing
