### ISSUE TITLE
Developer - Web App - Receive GitHub Webhooks

### ISSUE THREAD

**Issue by bryanjos** [revelrylabs/incentivize#65]
## Background
This task is to set up incentivize to receive GitHub webhooks in order to do what is needed with that data

## Scenario: A Repo Admin gives permission to Incentivize for WebHooks
- [ ] When a GitHub event happens
- [ ] Then incentivize is able to process the webhook event data

### Relevant Links
- https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/
- https://developer.github.com/v3/apps/installations/
- https://developer.github.com/v3/apps/

blocked by #93
blocked by #72

**Comment by bryanjos** [comment]
There is no front end to this right now. A person would have to go into server to create a project, get the secret key, and then add it to  repo

**Comment by Mcscott142** [comment]
Able to conenct a Repo via webhook. Moving to UAT.

**Comment by gerardramos** [comment]
holding in UAT until we have a front end for this.
