### ISSUE TITLE
Contributor/Supporter - Incentivized Projects - View Project List

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#66]
## Background 
Once a user has signed in and connected their Stellar account, they will want to peruse a list of projects to either support or contribute to.

Actual implementation of support and contribute buttons are in tickets #73 and #74

## Scenario: A user browses Projects for contributing or supporting
- [ ] When I select `Discover` on the Homepage
- [ ] Then I am directed to a list of projects

## Scenario: A user wants more details on a project before Contributing/Supporting
- [ ] When I select the title of the project
- [ ] Then I am directed to that Projects page `projects/<:id or :name>`

_Mock from @gerardramos_
![project_page_mock](https://user-images.githubusercontent.com/6877299/43526087-fd3e8baa-9568-11e8-827d-f337406e42b9.jpg)

**Comment by brittanygay** [comment]
Assigning to myself to work on the design pass

**Comment by brittanygay** [comment]
Working in sync/on the same branch as #67

**Comment by Mcscott142** [comment]
These are just stubbed out which is fine. Moving to UAT.
