### ISSUE TITLE
Contributor/Supporter - Incentivized Projects - View Project Page

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#67]
## Background
When a user wants more info on a project they can open the project show page from the index/list to see more details surrounding it. This page will grow as the product matures but to start we should show some project info, supporters, contributors and the amount totals for both. 

## Scenario: A user opens the project page to get more details on the project
- [ ] When I am directed to the Project page
- [ ] Then I see 
	- [ ] The Project Title
	- [ ] ~The Project Description via GitHub if available~
	- [ ] A link to the GitHub Repo for the Project
	- [ ] ~A list of current total reward levels for actions ~

To be added later: 
	- [ ] Support Project Button #74 
	- [ ] A link to a list of individual Project Funds  #91

_Mock from @gerardramos_ 
![project_detail_mock](https://user-images.githubusercontent.com/6877299/43589025-79142102-9633-11e8-9bb5-2cae09e5d885.jpg)

**Comment by Mcscott142** [comment]
Cutting this down on AC

**Comment by Mcscott142** [comment]
To include -repo link, current total reward levels for actions, link to a breakdown of individual sponsorships

**Comment by bryanjos** [comment]
@Mcscott142 there isn't anywhere where we defined getting a project description here

**Comment by Mcscott142** [comment]
I meant the Project description via GitHub if it's available. Updated AC. 

![create_a_new_repository](https://user-images.githubusercontent.com/6877299/43799685-d648d0ce-9a53-11e8-8893-22049399d7ca.png)

**Comment by brittanygay** [comment]
Assigning to myself to work on the design pass once Bryan's PR is merged

**Comment by brittanygay** [comment]
Working in sync/on the same branch as #66

**Comment by brittanygay** [comment]
**Update**:
I worked #74 before this ticket and I'm unfortunately out of time this week/have some other things to finish up so I'll have to complete the design pass for this ticket on Monday.

**Comment by brittanygay** [comment]
Working on the design pass for this page now

**Comment by Mcscott142** [comment]
Updated AC, keeping this basic for MVP. Moving to UAT.
