### ISSUE TITLE
Repo Admin - GitHub Integration - Instructions on Adding Webhook

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#72]
## Background
In the future, we'll want to give incentivize permissions on the project repo to create Webhooks itself (see #52). For MVP we will provide instructions for Repo Admin's to manually add the Webhook for incentivizing their projects. 

## Scenario: Admin Repo finds info on adding a Webhook to incentivize their project on 
- [ ] Given I have  selected connect repository in the Nav
- [ ] When I enter my owner and repository name 
- [ ] And select connect
- [ ] Then I see instructions/documentation on manually adding a Webhook for the incentivize app

**Comment by Mcscott142** [comment]
This technically passes. I created #103 to make it more obvious on what these fields want. Moving to UAT.

**Comment by gerardramos** [comment]
good call on #103. closing.
