### ISSUE TITLE
Contributor - Project Page/Index - Contribute to a Project

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#73]
## Background
When a Contributor finds a project they want to work on either via Project List or a Project Page they can select contribute and see all of the project pieces that are funded and the rewards associated with them. 

## Scenario: A contributor decides to contribute via Project page or list
- [ ] When I select `contribute`
- [ ] Then I am given different options for `Project Funds` where I can contribute
- [ ] When I select 'Start Contributing"
- [ ] Then I am directed to the GitHub Repo of the Project

**Comment by thomasknoll** [comment]
poker quit
joel [11:29]
what we said was: project page should have repo link, current total reward levels for actions, link to a breakdown of individual sponsorships

**Comment by Mcscott142** [comment]
Closing this one. List of rewards will be on project page as will a link to a Repo which is essentially the "contribute button"
