### ISSUE TITLE
Supporter - Project Page - Support a Project

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#74]
## Background
A supporter can choose to support a Project from the Project Page. When they choose to support a project they are given options to choose how many Lumens they'd like to add to the Project Fund and what the parameters are for earning them. The list will contain each GitHub Action and the amount of Lumen's they want to assign to that action. In order to save a Project Fund at least one GitHub action must have an amount greater than zero. 

## Scenario: Supporter chooses support project from Project Page
- [ ] When I select support
- [ ] Then I am given a list with:
- [ ] Each GitHub Action (Pull Request Open/Closed, Comment, Issue Opened/Closed)
- [ ] A Pledge amount for each action (numeric, defaulting to 0)
- [ ] When I save my pledges and parameters
- [ ] Given I have at least one pledge with a value greater than 0
- [ ] When I save
- [ ] Then my Project Fund is created

**Comment by Mcscott142** [comment]
List of actions w/ numeric inputs next to them. all start at 0, have to fill in 1 to continue.

**Comment by bryanjos** [comment]
@Mcscott142 one thing I think missing here is how many lumens the supporter wants to give PER contribution. Or is that what pledge amount is?

**Comment by Mcscott142** [comment]
@bryanjos I did mean that to be pledge amount. The intention is to have a line item in the list for each Github Action with a pledge amount next to it. Updated background and AC.

**Comment by Mcscott142** [comment]
Works for me. Updated AC.

**Comment by brittanygay** [comment]
I just pushed up some styling updates to this page, screenshots are in the PR. Assigning myself  because there may be some additional styling edits to finish up.

**Comment by bryanjos** [comment]
#113 tracks the remaining todos for this page

**Comment by Mcscott142** [comment]
I'm just getting what looks like a refresh everytime I hit support. 

![2018-08-10 17 07 44](https://user-images.githubusercontent.com/6877299/43983402-038639f0-9cc0-11e8-8f82-21aa6c91c339.gif)

**Comment by bryanjos** [comment]
@Mcscott142 sorry, missing deployment step. Should be ok now

**Comment by Mcscott142** [comment]
Looks good, moving to UAT.
