### ISSUE TITLE
Contributor - Account Page - Account details and History

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#77]
## Background
A Contributor's account page should be a good overall view of their activities on incentivize. They should see their Lumen balances as well as the history of their contributions. There will be a section for Supporting projects as well but that will be handled in #78 . 

## Scenario: A Contributor checks their Account page for stats and info
- [ ] Given I am directed to my account page
- [ ] Then I see a Contributions section with the following info:
	- [ ] Lumen Account Balance 
        _Note: For Account Balance, we don't need to show it twice. It will be taken care of here or in #78 but is listed as AC in both_
	- [ ] List of individual Contribution Earnings e.g. "Harmonium Pull Request - 10"
	- [ ] ~Projects contributed to with total earnings to date~

**Comment by bryanjos** [comment]
For sake of time, forgoing, `Projects contributed to with total earnings to date` for now
