### ISSUE TITLE
Contributor - Account - Remove Create Stellar Account

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#85]
## Background 
Per @bryanjos in https://github.com/revelrylabs/incentivize/issues/55#issuecomment-410298949, an account must have 1 lumen before it is activated. Soon, we will allow users to create a Stellar account directly through our application. For MVP we will have users bring an existing account and just connect it.  

## Scenario: A User signs in via GitHub and is directed to their Account page
- [ ] Given I have not connected an already existing Stellar Account
- [ ] When am directed to my Account
- [ ] Then I ONLY see the option to connect an existing Stellar Account
- [ ] And I do not see an option to create a Stellar Account

**Comment by Mcscott142** [comment]
Bryan Joseph [1:42 PM]
@Colin Scott for #55, we can either:
• Fund the account from our account (not costly now, but could be)
 * This would have to be done on the server to prevent exposing the funder’s secret  
• Make everyone bring their own stellar account
• Wait until a contribution happens. I don’t know the consequences of this one. Hopefully generating a key doesn’t produce duplicates ever

**Comment by bryanjos** [comment]
we can either:
* Make everyone bring their own stellar account
* Fund the account from our account (not costly now, but could be)
  * This would have to be done on the server to prevent exposing the funder’s secret  
* Wait until a contribution happens. 
  * I don’t know the consequences of this one. Hopefully generating a key doesn’t produce duplicates ever

Each has tradeoffs. I like first option, but it's not the most user-friendly.

Option 2 is the most user friendly, but may also have some extra security checks needed
Option 3 is also user friendly, but also requires us to check every time we need to query for info that the account exist. Which may not be too bad.

**Comment by Mcscott142** [comment]
For MVP maybe we should just enforce bring your own account. We can always iterate on it later.

**Comment by Mcscott142** [comment]
Updated AC and Title to remove Create Account Option. Original description:
>## Background 
>Per @bryanjos in https://github.com/revelrylabs/incentivize/issues/55#issuecomment-410298949, an account must have 1 lumen before it is activated. 
>- Maybe we just put the onus on people to add their own lumens to their accounts for MVP
>- Maybe we have the ability to drop them one? 
>- Maybe the Account just gets activated once they make a contribution and are >rewarded lumens
>## Scenario: TBD

**Comment by bryanjos** [comment]
@Mcscott142 Yeah I think this is best. I was thinking about option 3, but that also falls apart if we are not using lumens. We should at least give some instructions or links to creating a stellar account, but that can be a separate story. I think there are some concerns about that as well.

For mvp though, what is written here should be fine

**Comment by Mcscott142** [comment]
This will be tested with #55. Closing.
