### ISSUE TITLE
Supporter - Stellar Integration - Project Fund holding account

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#92]
## Background 
Research ticket. When a supporter makes a pledge to a project fund, the lumens opledged need to land somewhere. This is a research ticket for how that will work

## Scenario: Make a plan for a project fund "escrow"
- [ ] Research best ways to impelement the account to hold pledges for project funds
- [ ] Create ticket to score and implement

**Comment by thomasknoll** [comment]
not 100% the same, but this just recently came up in https://stellar.stackexchange.com/questions/1371/how-do-i-distribute-multiple-times

**Comment by bryanjos** [comment]
Something closer to this:
https://medium.com/wearetheledger/stellar-escrow-smart-contract-development-4c43ef32ac4b

I don't think we want to put the tokens into incentivize's owned account or in the incentivizer's account. We would want an account that is owned by incentivize's owned account that holds the funds. The incentivizer then puts the funds into that account and from there incentivize would be able to distribute funds when needed from that account for the purposes defined

**Comment by bryanjos** [comment]
Stellar docs has some examples as well:
https://www.stellar.org/developers/guides/walkthroughs/stellar-smart-contracts.html

**Comment by bryanjos** [comment]
Or to be more or less particular, whatever that thing in the real world of business is where you have a line of money to do things with that are only for a certain thing. Whatever that term is

**Comment by bryanjos** [comment]
https://medium.com/wearetheledger/stellar-escrow-smart-contract-development-4c43ef32ac4b

In our case, for each project fund creation we would:

* Create Fund Account
  * Make it so incentivize has to sign transactions to release funds
* Present the public key to the person funding the account in order to put funds in it

For each contribution that comes in, incentivize should be able to send sign transactions to send tokens to contributors

**Comment by bryanjos** [comment]
* Incentive needs an Owner Stellar Account
* Each project fund has it's own account. We would need to store public and private key (or maybe not private key since incentivize will have power to create transactions?)

**Comment by bryanjos** [comment]
@gerardramos you think we need to keep the secret key for project funds if the account incentivize uses has the ability to make transactions?

**Comment by gerardramos** [comment]
Let’s not store private keys of users accounts. 

Seems like we will need to store private keys for incentivize accounts or can we set the owner accounts up in a way where they only get funds back in case of time release / project abandonment?

**Comment by bryanjos** [comment]
No storing of private keys needed. I think I have a plan to move forward.

An escrow account that both the funder and incentivize has ability to make transactions. To update trust though, both would need to sign. Would give the funder the ability to back out funds if they really wanted to

**Comment by Mcscott142** [comment]
@bryanjos is this ready for a workable ticket? Can you help with the details a bit. 

Create Tickets for 
- [ ] Create and connect an Owner Stellar Account for Incentivize app
- [ ] Stellar Account is created and attached each time Project Fund is created
	* Incentivize owner account gives us the ability to manipulate the funds from here without the private key being stored

**Comment by bryanjos** [comment]
@Mcscott142 Yes, we can make tickets for:
* Create a Stellar Account for Incentivize
  * The public and secret will be stored in environment variables
* Create Project Fund
  * WHEN a supporter fills out the form to Support a project (#74)
  * AND all information is correct, 
  * THEN we create a project fund account in stellar
  * AND Signers will be Supporter and Incentivize with the following weights 
    * Supporter: 1,
    * Incentivize: 2
  * AND the account will have the following options set
    * Master Weight: 0
    * Low threshold: 1
    * Medium Threshold: 1 
    * High Threshold: 2
  * AND we present the public key of the fund to the user to add funds to it
  * AND we do not need the secret key of the project fund anymore at all

**Comment by bryanjos** [comment]
@Mcscott142 created #105 and #106

**Comment by bryanjos** [comment]
If tickets are score-able, moving this to QA
