### ISSUE TITLE
Developer - GitHub Integration - Use GitHub App for WebHooks

### ISSUE THREAD

**Issue by Mcscott142** [revelrylabs/incentivize#96]
## Background
The current plan is to use an Oauth app. When a user adds a repository in the app, they will get a webhook secret and instructions to add the webhook to github. This is covered in #65 #72 and #93. 

Via slack @jwietelmann suggested that using a GitHub app would be easier, but there may be some unknowns there. https://developer.github.com/apps/differences-between-apps/#webhooks

We do not need a Marketplace listing so this could remove the unknowns. 

## Scenario: Connect repositories to incentivize
- [ ] GIVEN I want to connect repositories to incentivize
- [ ] When I install the github app for me or for an organization
- [ ] Then I see my public repos are connected

**Comment by Mcscott142** [comment]
@jwietelmann @gerardramos @bryanjos We are continuing on the path of Oauth app unless we decide it's easier to use a GitHub app. Drop your reasons for using/not using a GitHub app in ticket comments. 

If we decide to go this way I need help working out the AC.

**Comment by bryanjos** [comment]
We should definitely do this

**Comment by bryanjos** [comment]
Looks like with a github app the oauth login is a drop-in replacement outside of not having access to a user's emails.

**Comment by bryanjos** [comment]
From there, there are other considerations around installations. I'm not sure how to get user to the screen that installs a github app yet though

**Comment by bryanjos** [comment]
Never mind, I think I see now. The app gets a public page

**Comment by bryanjos** [comment]
We would need to capture information about the installation. We can make a table. Probably the following is enough?

- installation_id
- github_login
- type #webhook has a type field. Example shows value as `User` so assuming it can also be `Organization`

The installation webhook also has repositories on it as well. This is probably what we would use to add repos to incentivize.

There is another webhook for when repos are added or removed from an installation. We would have to look out for those as well

**Comment by bryanjos** [comment]
I created a new issue for github app login (#156) and saving this one for webhook talks

**Comment by brianberlin** [comment]
Just adding a note here... I ran into an issue with a repository that i've made a minor contribution to, stellar/docs, which i don't have access to add the necessary webhooks for incentivize to track

**Comment by bryanjos** [comment]
We may be able to make a better flow using either the `User authorization callback URL` or the `Setup URL` for github apps. I'm thinking the initial set up "Call to Action" can be a button that links to the github app. Once installed, we can go about setting up things from one of the above redirects to finish creating a user

**Comment by bryanjos** [comment]
@Mcscott142 you should probably test this out on production for now because of ssl issues on staging

**Comment by Mcscott142** [comment]
I can get the authorize screen, I can configure settings via GitHub. How do I add my Repo once I've given Authorization? Maybe it's still there but not clear to me how to use this.

**Comment by bryanjos** [comment]
@Mcscott142 anything you selected when installing the github app should be added automatically

**Comment by bryanjos** [comment]
If you look at the `Discover` page, you should see them

**Comment by Mcscott142** [comment]
Got it Got it. I'm going to spin up a ticket for an area where you can see all of your connected repos. Passes, closing.
